package com.dazzlebloom.apiresponse

import com.google.gson.annotations.SerializedName

data class CreateListModel( @SerializedName("listing_id") val listing_id : String,
                            @SerializedName("post_content") val post_content : String,
                            @SerializedName("post_excerpt") val post_excerpt : String,
                             @SerializedName("uid") val uid : Int,
@SerializedName("post_title") val post_title : String,
@SerializedName("tags") val tags : Array<String>,
@SerializedName("category") val category : Array<Int>,
@SerializedName("phone_number") val phone_number : String,
@SerializedName("whatsapp_number") val whatsapp_number : String,
@SerializedName("listing_type") val listing_type : String,
                            @SerializedName("feature_list") val feature_list : String,
                            @SerializedName("website") val website : String,
                            @SerializedName("price") val price : String,
                            @SerializedName("contact_email") val contact_email : String,
                            @SerializedName("city") val city : String,
                            @SerializedName("address_line_1") val address_line_1 : String,
                            @SerializedName("address_line_2") val address_line_2 : String,
                            @SerializedName("zip_code") val zip_code : String,
                            @SerializedName("additional_info") val additional_info : String,
                            @SerializedName("lat") val lat : String,
                            @SerializedName("long") val long : String,
                            @SerializedName("attached_image_id") val attached_image_id : Array<String>,
                            @SerializedName("attached_image_title") val attached_image_title : String,
                            @SerializedName("attached_image_as_logo") val attached_image_as_logo : String,
                            @SerializedName("attached_video_id") val attached_video_id : String,
                            @SerializedName("linkedin_link") val linkedin_link : String,
                            @SerializedName("instagram_link") val instagram_link : String,
                            @SerializedName("youtube_link") val youtube_link : String,
                            @SerializedName("twitter_link") val twitter_link : String,
                            @SerializedName("facebook_link") val facebook_link : String,
                         )
